### PR TITLE
Remove Webpack and ES2015 features not supported by Node

### PR DESCRIPTION
**Pull request by igorlima**
Just removing webpack and ES2015 features not supported by Node.
Before it was needed to run `webpack` and then `node server.build.js`.
Now it's needed to run only `node server.js` without transpeling the ES2015 features.

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Hi @igorlima. Can you please update the old PR so that I can take a look at it on the repository?

**Comment by igorlima** [comment]
@AurelioDeRosa what do you need by _update the old PR_? I didn't get what you said.

**Comment by AurelioDeRosa** [comment]
Hi @igorlima. I meant that you should update your [pull request in the js-peers repository](https://github.com/sitepoint-editors/js-peers/pull/50), instead of creating a new article in your own repository. Thank you

**Comment by igorlima** [comment]
I'm not creating a new article. I'm just updating the [code](https://github.com/igorlima/todo-graphql-server/) of the [live demo](https://todo-graphql-server.herokuapp.com/graphql).

Also I updated the article removing all references of webpack: https://github.com/igorlima/js-peers/commit/79ad2ce338cbe2a0d5047a40302be2fb5d70c1d3

Why I removed Webpack reference? Because you told me via email:

> In addition, I've tried to run your application and when I execute the command `node server.js` I receive an error (on the console).

Without Webpack, there is no need to transpile the code, so you can simply run `node server.js`.

**Pull request merged**
